# run pre-commit on changed files
name: run pre-commit workflow
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pre-commit/action@v3.0.1
        name: Configure and run pre-commit on changed files
        with:
          extra_args: --color=always --from-ref ${{ github.event.pull_request.base.sha }} --to-ref ${{ github.event.pull_request.head.sha }}